### ISSUE TITLE
Architecture Definition

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#1]
Come up with the architecture for the app. The 2020 apps see's a big shift where we will be using our own backend and not firebase.

Architecture Highlights:

- Modularizing the app

- Libraries to be used

- Dependecy Injection

- Testing

The write up will be in the [README](https://github.com/droidconKE/droidconKE2020App/blob/master/README.md)

@michaelbukachi Suggestions are welcome. This is the very first step for development

**Comment by jamesnyakush** [comment]
Let me have an input to this one  the following are my suggestions:

1. Write a list of features that we want to include in the app and timelines for each feature.
2. Have a one direction Readme/Docs that will help contributors to see which feature to contribute.
3. Have a wireframe that we are going to be achieving.

**Comment by wangerekaharun** [comment]
All of that is in Pipeline

**Comment by jamesnyakush** [comment]
My suggestions on the DI to be used would prefer [`Kodein](https://kodein.org/Kodein-DI/?6.5/android)

**Comment by wangerekaharun** [comment]
We will come to that, you can add a kodein branch on the [droidconKE2019App](https://github.com/droidconKE/droidconKE2019App) to begin with :)

**Comment by jamesnyakush** [comment]
> All of that is in Pipeline

Thats great

**Comment by jamesnyakush** [comment]
> We will come to that, you can add a kodein branch on the [droidconKE2019App](https://github.com/droidconKE/droidconKE2019App) to begin with :)

i'll be taking a look at this first of all and understand ur history as droidconKE u app architecture for the previous years to have a clear picture of what we are going to be building

**Comment by wangerekaharun** [comment]
> > We will come to that, you can add a kodein branch on the [droidconKE2019App](https://github.com/droidconKE/droidconKE2019App) to begin with :)
> 
> i'll be taking a look at this first of all and understand ur history as droidconKE u app architecture for the previous years to have a clear picture of what we are going to be building

Okay no problem. Feel free to do so

**Comment by michaelbukachi** [comment]
@jamesnyakush  We are using koin for DI. It works really well.

**Comment by jamesnyakush** [comment]
> @jamesnyakush We are using koin for DI. It works really well.

Its ok @michaelbukachi  though used to kodein dont know why but i'll give it a shot

**Comment by jamesnyakush** [comment]
@wangerekaharun and @michaelbukachi  give me leads on the project would love to contribute but i can't see the trailing slash

**Comment by michaelbukachi** [comment]
We are finishing up with design first. Once that is done we'll dive straight into development. We'll let you know before then.

**Comment by jamesnyakush** [comment]
@michaelbukachi thanks for ur leads otherwise have a greate day

**Comment by wangerekaharun** [comment]
> @wangerekaharun and @michaelbukachi give me leads on the project would love to contribute but i can't see the trailing slash

Last years app will be a good start. We usually port most of the improvements done there

**Comment by jamesnyakush** [comment]
Ok on it

**Comment by jamesnyakush** [comment]
Any updates

**Comment by wangerekaharun** [comment]
Still on design phase

**Comment by jamesnyakush** [comment]
Great and this design phase has taken time

**Comment by JabezNzomo99** [comment]
Koin for DI is seamless and really easy to set up and use.

**Comment by wangerekaharun** [comment]
@jamesnyakush We've started off with the architecture part of the app. Feel free to check.

**Comment by jamesnyakush** [comment]
@wangerekaharun  great am watching

**Comment by tamzi** [comment]
We need a better title for this maybe: **Architecture Definition** @wangerekaharun @jamesnyakush @michaelbukachi @JabezNzomo99

**Comment by wangerekaharun** [comment]
> We need a better title for this maybe: **Architecture Definition** @wangerekaharun @jamesnyakush @michaelbukachi @JabezNzomo99

Done. @JabezNzomo99  Is working on something interesting on the same

**Comment by tamzi** [comment]
dont think it is yet, any submissions with links?

**Comment by wangerekaharun** [comment]
Still waiting on @JabezNzomo99

**Comment by wangerekaharun** [comment]
App architecture is fully laid out on the [README](https://github.com/droidconKE/droidconKE2020App/blob/master/README.md)
