### ISSUE TITLE
Setup App Modules

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#10]
Setup the respective app modules following the specifications on the [Architecture Introduction](https://github.com/droidconKE/droidconKE2020App#architecture-introduction).

For Feature Modules, we have the following features :

- Home
- Feed
- Sessions
- About
- Speaker Details
- Session Details
- User Sessions
- Team Member Details
- Auth - with Sign Up,Sign In and Forgot Password
- Feedback - event and session feedback
-

**Comment by wangerekaharun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setup App Modules](https://trello.com/c/yv9jgNTj/3-setup-app-modules)

**Comment by jamesnyakush** [comment]
great progress

**Comment by wangerekaharun** [comment]
Addressed by #17
