### ISSUE TITLE
Building an appBundle

### ISSUE THREAD

**Issue by michaelbukachi** [droidconKE/droidconKE2020App#106]
It seems the duplicate resources is constantly being introduced into the codebase. I'm creating an issue dedicated to fixing this.
To recreate this error:
Run `./gradlew bundleDebug` or build an app bundle using AS.
This command should run before doing a PR.
@wangerekaharun let's pin this and always reference it all PRs. I'm gonna add an action so that CI checks for this.

**Comment by wangerekaharun** [comment]
The theme issues re-introduced the issues once again, was checking.in the changes today. Maybe we can also add lint checks for every PR so that before even merging, the issues are already pointed out. Or add the command gor building also as a check if it doesn't pass, the person has to resolve all the issues

**Comment by michaelbukachi** [comment]
Let me add the CI check.
I'm not very familiar with linting, what command do I need to run terminal to do lint checks?

**Comment by muth0mi** [comment]
You have to annotate the methods I think. Not quite sure though. I have only explored this in theory.

**Comment by wangerekaharun** [comment]
Was thinking of [Ktlint](https://ktlint.github.io/) and [Dekt](https://github.com/arturbosch/detekt). With this we can even write our custom lint rules. Will be handling this after am done with the toolbar issue. The custom view part has  given me a very long weekend

**Comment by michaelbukachi** [comment]
Haha. Custom views do that you :satisfied: Anyway, let's setup an issue  for Ktlint/Dekt
