### ISSUE TITLE
Migrate Splashscreen Activity from Activity to Fragment

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#109]
Since we are using Single Activity Architecture, this issue addresses migrating the activity to a fragment and adding the necessary Navigation Component logic.

**Comment by michaelbukachi** [comment]
Hmm. How will this work? I thought the splash screen is supposed to be on a screen with no logic whatsoever. Moving it the a fragment will imply that HomeActivity has to be loaded first, meaning there will always be white screen when the app starts.

**Comment by wangerekaharun** [comment]
Okay that makes sense. Closing this now
