### ISSUE TITLE
App Crashes Upon Clicking an Organizer in About Page

### ISSUE THREAD

**Issue by muth0mi** [droidconKE/droidconKE2020App#114]

**Comment by wangerekaharun** [comment]
@muth0mi Can you give steps to reproduce this. Tested this and everything is okay on my end.

**Comment by muth0mi** [comment]
#### To reproduce the issue: 
1. Launch the app (build from :develop) 
1. Navigate to **About** page.
1. Scroll to the **organizing Team** section
1. Click on one of the organizer cards

#### Expected behaviour (Well, exepected to reproduce :-D)
The app should crash with the following exception (excerpt from in the logcat)
![image](https://user-images.githubusercontent.com/18559830/78712091-bde46e00-7920-11ea-899b-2f0d0d9cb04e.png)

#### Screenshots
1. 
![Screenshot_20200407-224012](https://user-images.githubusercontent.com/18559830/78712638-9510a880-7921-11ea-8991-ce47c7545151.jpg)

1.
![Screenshot_20200407-224028](https://user-images.githubusercontent.com/18559830/78712661-9cd04d00-7921-11ea-9830-bf8c8570b7bc.jpg)

1.
![Screenshot_20200407-224040](https://user-images.githubusercontent.com/18559830/78712681-a659b500-7921-11ea-9532-9b24fe9c249e.jpg)

**Comment by wangerekaharun** [comment]
Can you try a fix for this using your phone. Retried the same steps with my phone and its working with my phone

**Comment by muth0mi** [comment]
I'll try on an emulator and with a different device and see if it persists.

**Comment by Anniekobia** [comment]
Hi @muth0mi , I have also tried the same steps but it works fine on my end

**Comment by ben-mathu** [comment]
try a rebase from develop, that is if the repository you are working on is not updated.

And also if the screenshots are correct there should 12 not 10 organizers, because i added the number of organizers in the createOrganizer() method, thats why i think your app is not up to date.

**Comment by Anniekobia** [comment]
> try a rebase from develop, that is if the repository you are working on is not updated.
> 
> And also if the screenshots are correct there should 12 not 10 organizers, because i added the number of organizers in the createOrganizer() method, thats why i think your app is not up to date.

@muth0mi

**Comment by wangerekaharun** [comment]
@muth0mi What's the status of this? Should i close this?

**Comment by muth0mi** [comment]
Yes, the issue doesn't occur on other devices I've tested with. The device I noticed the issue on had a custom ROM and I guess that's what caused the issue.
