### ISSUE TITLE
Migrate to Gradle KTS

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#12]
After Module setup and app flow is complete, Migrate from using groovy to using Kotlin DSL Gradle Plugin.

**Comment by wangerekaharun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate to Gradle KTS](https://trello.com/c/7zfubWTp/5-migrate-to-gradle-kts)

**Comment by jamesnyakush** [comment]
this is great

**Comment by wangerekaharun** [comment]
@chepsi also make sure you add the docs for this, to assist those who want to add dependencies later on in the project

**Comment by chepsi** [comment]
Can we close this issue?

**Comment by michaelbukachi** [comment]
Yeah we can.
