### ISSUE TITLE
Setup Release Automation

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#129]
Now that we have published the app on playstore, time to Automate future releases. Suggested workflow :

Stable - Master branch :
Final stable release
 Beta -  Pre-Release branch :
For the App testers outside droidconKE.
 Alpha - Develop branch:
 for developer builds and guys within droidconKE and some controlled UX testing.

**Comment by wangerekaharun** [comment]
@michaelbukachi After PR #132 This is now good to start.

**Comment by michaelbukachi** [comment]
Great! I'll start working on this as soon as it's merged.
