### ISSUE TITLE
Implement Fetch Organizing Team

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#138]
Add logic to fetch organizers on the app using the API endpoints on the network module.This tasks covers adding the logic on repo, viewmodel and on view too and adding the necessary tests.

**Comment by muth0mi** [comment]
Organizer's recyclerview has overscroll overlays yet it's not scrollable. 
Whoever will be handling this issue could fix that as well. It's a tiny thing most won't notice but it goes far for UX.

**Comment by wangerekaharun** [comment]
> Whoever will be handling this issue could fix t

Scroll overlay was removed since the number of organizers is fixed.Check on #158 and #159

**Comment by muth0mi** [comment]
I'm working on #162 right now and I can notice them

**Comment by muth0mi** [comment]
![Screenshot_20200617-194721_droidconKE2020](https://user-images.githubusercontent.com/18559830/84926713-7aeb0780-b0d4-11ea-862f-ba875385ec32.png)
![Screenshot_20200617-194729_droidconKE2020](https://user-images.githubusercontent.com/18559830/84926719-7cb4cb00-b0d4-11ea-9fd4-e54a07f888c8.png)

**Comment by wangerekaharun** [comment]
Alright got what you meant.
