### ISSUE TITLE
Implement Fetch Speakers

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#139]
Add logic to fetch event speakers on the app using the API endpoints on the network module.This tasks covers adding the logic on repo, viewmodel and on view too and adding the necessary tests.

**Comment by michaelbukachi** [comment]
@wangerekaharun I think we need to break down this task even further.

**Comment by wangerekaharun** [comment]
> @wangerekaharun I think we need to break down this task even further.

No problem we can always break them down in case there is something left out.
