### ISSUE TITLE
Add logic to logout from app

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#144]
Once a user is signed in, implement logic to logout the user from the app which calls logout from the API

**Comment by Rita-Okonkwo** [comment]
Hi can I work on this?

**Comment by wangerekaharun** [comment]
Yes you can start working on it.

**Comment by Rita-Okonkwo** [comment]
Alright thank you

**Comment by Rita-Okonkwo** [comment]
Hello, I have gone through the app but I cannot see a logout menu. Is that something that I need to add too?

**Comment by wangerekaharun** [comment]
> Hello, I have gone through the app but I cannot see a logout menu. Is that something that I need to add too?

Hello too, logic is that when one is signed out, clicking the account icon should show logout option. You can share your trello username so that i can add you to the board where we have more resources that cannot be shared publicly due to marketing purposes
