### ISSUE TITLE
Add fetch keynote speaker on HomeFragment

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#151]
Add option to fetch the keynote speaker from the server through the API

**Comment by wangerekaharun** [comment]
@michaelbukachi since #206 has addressed part of this, what's the best way to fetch the actual keynote speaker?

**Comment by michaelbukachi** [comment]
@wangerekaharun We have two options, either we add a new endpoint and change the logic accordingly or we add a new field to speakers e.g `keynote` which can be true or false.

**Comment by wangerekaharun** [comment]
> @wangerekaharun We have two options, either we add a new endpoint and change the logic accordingly or we add a new field to speakers e.g `keynote` which can be true or false.

Alright let us notify Magak of the same on the group

**Comment by wangerekaharun** [comment]
@michaelbukachi the session's response has a key if a session is a keynote session. So we can get the speaker for the session and display the keynote speaker

**Comment by michaelbukachi** [comment]
Alright. I'll create a PR.
