### ISSUE TITLE
Fetch sponsors on HomeFragment

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#154]
Add logic to fetch event sponsors on HomeFragment from the server through an API

**Comment by ben-mathu** [comment]
@wangerekaharun and @michaelbukachi i think we might be duplicating implementations. Issue #146 has the same requirements, fetching sponsors from server.

**Comment by michaelbukachi** [comment]
@ben-mathu You are right. This task should actually depend on the other one.

**Comment by michaelbukachi** [comment]
This task should involve removing the use of dummy data .

**Comment by ben-mathu** [comment]
So what i need to add here is implementation and testing for **data sources**, **repository**, **viewmodel** and **ui**, and **removing dummy data**. Are these the requirements for this tasks?

**Comment by michaelbukachi** [comment]
> So what i need to add here is implementation and testing for **data sources**, **repository**, **viewmodel** and **ui**, and **removing dummy data**. Are these the requirements for these tasks?

Yes. That's the gist of it. I

**Comment by michaelbukachi** [comment]
I'm working on the task for sign in/out. I'll do a PR today since you might need it for your task.

**Comment by wangerekaharun** [comment]
> I'm working on the task for sign in/out. I'll do a PR today since you might need it for your task.

Great after this it would be easy to do the rest of the tasks
