### ISSUE TITLE
Consistent Margins and Paddings

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#157]
This issue addresses the issue of not having inconsistent margins and padding. This also have to match the designs. Some of the screens affected are ;

- Padding Below the organized by card on home fragment
- Sponsors card add bottom and top padding on home fragment
- Bottom margin/padding on last sessions card on sessions fragment
- Session Details Check on paddings/margin on this
- Bottom marging/padding on last card on feed fragment.

**Comment by michaelbukachi** [comment]
Can we highlight the screens which need to be fixed?

**Comment by wangerekaharun** [comment]
> Can we highlight the screens which need to be fixed

Updated  the description with the specific screens as is on the feedback document
