### ISSUE TITLE
Make Bottom Navigation Navigate to respective destinations 

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#19]
After #18 next is to make the bottom navigation view to navigate to the different destinations

**Comment by wangerekaharun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make Bottom Navigation Navigate to respective destinations](https://trello.com/c/TbaTo8ut/8-make-bottom-navigation-navigate-to-respective-destinations)

**Comment by JabezNzomo99** [comment]
I'll start working on this
