### ISSUE TITLE
What modularization approach should we implement?

### ISSUE THREAD

**Issue by JabezNzomo99** [droidconKE/droidconKE2020App#2]
I am thinking of modularization by feature where each feature module has its own data layer, repository layer and UI layer. Shared logic can be placed in the base module.

**Comment by wangerekaharun** [comment]
We have two approaches that stood out:

1. app, base, feature and data modules - domain and data are in the data modules where as feature module has presentation layer
2. app,base,feature - with each feature having its own domain, presentation and data logic

So the approach you are saying is the second one which we can choose it.

**Comment by jamesnyakush** [comment]
2. app,base,feature - with each feature having its own domain, presentation and data logic.


this could be  great but still room for arguments

**Comment by wangerekaharun** [comment]
@JabezNzomo99 is working on the full write-up on the same on the final proposed structure then we can go ahead.

**Comment by jamesnyakush** [comment]
great on the wait list

**Comment by wangerekaharun** [comment]
@JabezNzomo99 how far are you on this?

**Comment by wangerekaharun** [comment]
The approach chosen is on the[Architecture Introduction section](https://github.com/droidconKE/droidconKE2020App#architecture-introduction)
