### ISSUE TITLE
About Module Design

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#29]
Implementing the about module design

**Comment by ben-mathu** [comment]
Hi @wangerekaharun , I was wondering if this was the design phase where you do sketches and drawings, or is it an design implementation in code

**Comment by wangerekaharun** [comment]
Implementation of the design in code

**Comment by jamesnyakush** [comment]
mind sharing the design as a pdf on the readme

**Comment by wangerekaharun** [comment]
Will sort this in the course of the week
