### ISSUE TITLE
Auth Module Design

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#30]
Implementing the design for auth module. This modules has the following screens/pages

- Sign up
- Sign in
- Forgot Password
- New Password

**Comment by chepsi** [comment]
Since we have decided to use Google authentication, I am closing this issue.

**Comment by wangerekaharun** [comment]
@chepsi but we still need a screen with sign in with google button

**Comment by chepsi** [comment]
Should we reopen the issue? I was thinking more of a popup window with the sign in with google

**Comment by wangerekaharun** [comment]
Let me reopen. John will have something on the design. So we'll wait

**Comment by chepsi** [comment]
Safe to close this issue now?

**Comment by wangerekaharun** [comment]
Yes its way safe. However will create an additional for improving the dialog,or you can compare the dialog used on last year's app and improve accordingly :-)
