### ISSUE TITLE
Home Module Design

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#33]
Implementing the design for home module. This module has the following features :

- User can see count down (pre-event)

- User can see offers and promos

- User can see CFP (pre-event)

- User can see keynote speakers (pre-event)

- User can click link to apply as a speaker  (pre-event)

- User can see sponsors

- User can link to sign-up as a sponsor

- User can see droidcon ke logo at the top left corner 

- User speakers of current active sessions (During the event)

- User can see navigation for viewing today's session (During the event) 

- User can can click logo at the top right corner and see sign in page or the sign out option 

- User can speakers (during event)

- User can speakers list (first three should be the speakers for the current active sessions)

- User can see the feedback action and be able to click on it. 

- User should be able to navigate to the all sessions screen 

- User should be be able to navigate to the all speakers screen

- User should be able to switch to night mode

**Comment by michaelbukachi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Home Module Design](https://trello.com/c/RKRmzx6O/16-home-module-design)
