### ISSUE TITLE
Setup HomeViewModel in home module

### ISSUE THREAD

**Issue by michaelbukachi** [droidconKE/droidconKE2020App#45]
This ViewModel should handle all the logic for the home page. Use of `livedata` + `data binding` should be used to make binding to the UI easier. The logic in this ViewModel includes:

- Displaying/Hiding promos when available
- Showing CFP card for a given duration.
- Handling all click and navigation events
- Loading of data for any recyclerview
- Logic for handling night mode

**Comment by muth0mi** [comment]
Is it ok to modify the recyclerView adapters to use listAdapter and diffCallback? And to introduce databinding in the adapters?

**Comment by muth0mi** [comment]
> Showing CFP card for a given duration.

When should the card be hidden and shown?

**Comment by muth0mi** [comment]
Also, the promos? Is it a single promotion at a time or several in sort of a carousel?
