### ISSUE TITLE
Setup state in SplashScreenActivity

### ISSUE THREAD

**Issue by michaelbukachi** [droidconKE/droidconKE2020App#57]
Ideally, due to the nature and timeframe of the splash screen animation, it should only be shown the first time a user launches the app. We to  use the preferences class from #56 to store/retrieve state. To determine whether the animation is shown. In situations where an animation is not shown, a splash screen image should be shown instead (or a shorter timeframe for the animation can be used).

**Comment by chepsi** [comment]
Closing this issue.
