### ISSUE TITLE
Dynamic Toolbar Design

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#59]
Add toolbar. The toolbar changes  from screen to screen. The following are the designs for the toolbar.

- Home(Before Event)
![Screenshot from 2020-03-23 10-30-04](https://user-images.githubusercontent.com/15122455/77293023-8788db00-6cf2-11ea-8999-e9f288c5e91c.png)

- Home(During Event)
![Screenshot from 2020-03-23 10-30-36](https://user-images.githubusercontent.com/15122455/77293070-a4bda980-6cf2-11ea-86dd-b85c0471d753.png)

- Feed
![Screenshot from 2020-03-23 10-33-00](https://user-images.githubusercontent.com/15122455/77293092-b010d500-6cf2-11ea-8d2d-67765bb4fe71.png)

- Feedback
![Screenshot from 2020-03-23 10-35-12](https://user-images.githubusercontent.com/15122455/77293134-c61e9580-6cf2-11ea-9d19-0685c2fe8117.png)

**Comment by odaridavid** [comment]
On this
1. The home before event design what do those three figures represent?
2. What do the icons on the extreme right do,the purple ones and green one
3. Where can the assets be found ,the feedback background moreso

**Comment by wangerekaharun** [comment]
To address your queries:
1. The three figures are the countdown to #droidconKE2020
2. They represent user icons depending on gender(male, female) when a user has not signed in.
3. Assets can be availed upon request for the person working on the issue.
