### ISSUE TITLE
Improve Filter Session Design

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2020App#66]
Improving the Filter Design to closely match the Design.Here are the are a couple of issues to look at.
- Background of the bottom sheet
- Filter chips to be reflect what is on the design currently
- Bottom sheet to cover whole screen

**Comment by moyheen** [comment]
@wangerekaharun please where can I find the design for this?

**Comment by wangerekaharun** [comment]
Here's the design :
![download](https://user-images.githubusercontent.com/15122455/77420017-613e6a80-6dda-11ea-906a-6a71f26af384.png)

**Comment by muth0mi** [comment]
Implementation on #113 is comping up pretty neatly. 
@wangerekaharun :+1: :+1:
