### ISSUE TITLE
Common Communication Channel

### ISSUE THREAD

**Issue by ben-mathu** [droidconKE/droidconKE2020App#73]
Should we have a common communication platform for updates and general questions? I was wondering if we could use slack, or create a group on telegram.

This would keep everyone on here updated on what's going on.

**Comment by wangerekaharun** [comment]
There's a whatsapp group for this, let me know if you want to be added there.

**Comment by ben-mathu** [comment]
i have sent you my number on telegram.

**Comment by wangerekaharun** [comment]
Okay
