### ISSUE TITLE
Consistent Styling

### ISSUE THREAD

**Issue by odaridavid** [droidconKE/droidconKE2020App#83]
Concerning color resources, I noticed  duplication in the feature modules and overriding of the ```colorPrimary``` ,```colorPrimary```,and ```colorAccent``` which have the default colors on project creation.
My suggestion would be moving this resources to the app module and adopting material theme attributes for the primary and secondary colors and use them consistently throughout the app.
What do you think of this?

**Comment by wangerekaharun** [comment]
There's is a branch (issue-78) addressing all the styling Issues. We're yet to move fully to material theme. @odaridavid you can create an issue on the same and if in position to work on the same, we are always happy to see a PR -:)

**Comment by odaridavid** [comment]
Awesome ,let me check it out first.

**Comment by odaridavid** [comment]
Seems there is still some color resource duplication on the issue-78 branch,Ill raise a PR on it with this issue attached.

**Comment by wangerekaharun** [comment]
Its still Work In Progress but yes create a PR to adrress the same, @michaelbukachi can give more context on the same.

**Comment by michaelbukachi** [comment]
As @wangerekaharun  just raise a PR with necessary corrections. It can be against #78 branch.

**Comment by odaridavid** [comment]
Alright,will do

**Comment by muth0mi** [comment]
Is this PR merged to master? I could go ahead and implement a dark mode.

**Comment by odaridavid** [comment]
This issue was to mainly address styling consistency
Another issue will be raised for  adopting a material theme fully ,for dark
theme you can raise a different issue for it as its a feature request

**Comment by muth0mi** [comment]
Alright

**Comment by EdwardMuturi** [comment]
working on the style consistency issue using material theming. will push the branch later.
