### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by muth0mi** [droidconKE/droidconKE2020App#87]
Let's add a dark theme variation to the app

**Comment by muth0mi** [comment]
I think a matching status bar and toolbar color look way better. I'll go for that if nobody has any objections

**Comment by odaridavid** [comment]
You can check on issue #89 on migrating to a material theme that was the initial plan then once thats done moving to a dark theme will be easier since it means providing alternate resources for it and hooking it up with the settings screen

**Comment by muth0mi** [comment]
Alright. I'll make the PR with whatever I have implemented then we can pick it up on #87

**Comment by wangerekaharun** [comment]
Before @muth0mi you migrate i would like to share the design with you in person. It has a dark theme variation so that you can follow the design specs. Will share the same with @odaridavid

**Comment by muth0mi** [comment]
Please do.

**Comment by wangerekaharun** [comment]
Write me an email please

**Comment by muth0mi** [comment]
The dark mode toggle is currently on the toolbar for quick testing but will later move to the settings page.

**Comment by wangerekaharun** [comment]
For the toggle we will create a separate task for switching to dark theme. We were supposed to use gestures for doing the switch

**Comment by muth0mi** [comment]
How should the gestures work?

**Comment by wangerekaharun** [comment]
Drawing gestures on the screen. Common gestures include drawing a letter C to open a camera app.

**Comment by muth0mi** [comment]
I'm not quite sure... but I think having a canvas (for drawing the gestures) on top of the Navhost fragment will block a user from interacting with the content below (the main content).

How about we go with shake? Shake your phone to switch between dark/light modes.

**Comment by wangerekaharun** [comment]
We'll discuss more in details on that task

**Comment by muth0mi** [comment]
Can I implement the 'shake' as a place holder and remove the toggle icon from the toolbar?

**Comment by wangerekaharun** [comment]
Let it maintain on the icon. No need for double effort for something that will be re-done later

**Comment by muth0mi** [comment]
Ok
