### ISSUE TITLE
Migrate to a material theme

### ISSUE THREAD

**Issue by odaridavid** [droidconKE/droidconKE2020App#89]
This addresses the application theme moving from appcompat attributes to material theme attributes as well as defining the apps primary and secondary colors

**Comment by EdwardMuturi** [comment]
Followed material theming guidelines. I have moved most of the attributes to the new material attributes.

have you started working on this? Maybe I can save you the hassle.

**Comment by wangerekaharun** [comment]
To avoid double effort @EdwardMuturi wait for @odaridavid to give you a status update on the same

**Comment by EdwardMuturi** [comment]
okay, I already had a branch with some of the changes done. Just following up to see how I can share them instead of creating duplicate PRs

**Comment by wangerekaharun** [comment]
Great


Lets wait for @odaridavid to update on the status of this

**Comment by EdwardMuturi** [comment]
noted

**Comment by odaridavid** [comment]
You can just raise the PR and we'll review it.
I was holding on this cause the changes to the color scheme I made aren't
reflecting on develop and will affect the Dark theme issue.
We'll need to find a way to sync all this.

**Comment by wangerekaharun** [comment]
@odaridavid Merged the PR so you can proceed with this, there are however some comments on the PR #92 which can be addressed by this issue too.

**Comment by odaridavid** [comment]
Awesome,ill check them out.For this ill pull off develop compare with the changes made on branch issue-78 and address any inconsistencies as well

**Comment by michaelbukachi** [comment]
@odaridavid I've just realized there's duplicate resources. So I've had to revert the MR. This error can only be detected the moment you try to build an app bundle or run UI tests. For the next PR, remember to run `./gradlew bundleDebug` to make sure there are no duplicate resources in different modules.

**Comment by odaridavid** [comment]
Let me check on that and change accordingly
